"""Plant realistic bugs and require a test to FAIL for each (a green test proves nothing until it
has been made to fail). Restores every file in a finally block. Standard library only.

    python migration/mutations.py
"""

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MUTATIONS = [
    ("a resend rebuilds the envelope with a fresh id", "eco_publisher.py",
     "events = [json.loads(e) for _, _, e in batch]", "events = [dict(json.loads(e), id=str(uuid.uuid4())) for _, _, e in batch]", "TEST_ECO_PUBLISHER.py"),
    ("employees invented from attendance alone", "eco_publisher.py",
     "if emp and status:", "if emp:\n            status = status or 'Active'\n        if emp and status:", "TEST_ECO_PUBLISHER.py"),
    ("versions may go down", "eco_publisher.py",
     "version = max((row[1] if row else 0) + 1, int(time.time() * 1000))", "version = 1", "TEST_ECO_PUBLISHER.py"),
    ("minutes rounded silently", "eco_publisher.py",
     "if float(minutes).is_integer() and minutes >= 0:", "if minutes >= 0:", "TEST_ECO_PUBLISHER.py"),
    ("a KPI of the original application changes", "PROJECT.json",
     '"Employees observed"', '"Employees seen"', "TEST_MIGRATION_EQUIVALENCE.py"),
    ("absence is no longer explicit-only", "PROJECT.json",
     '"Absent"', '"Leave"', "TEST_MIGRATION_EQUIVALENCE.py"),
    ("registry columns get TEXT affinity (1 becomes '1')", "hr_core/registry.py",
     'cols = ", ".join(f for f in fields if f not in ("code",))', 'cols = ", ".join(f"{f} TEXT" for f in fields if f not in ("code",))', "TEST_HR_REGISTRY.py"),
    ("a stale version overwrites a newer one", "hr_core/registry.py",
     'if op.get("expected_ver") is not None and (not cur or cur["ver"] != op["expected_ver"]):', 'if False:', "TEST_HR_REGISTRY.py"),
    ("a crash after the commit point is not repaired", "hr_core/registry.py",
     'done, last = self.applied_seq(), self.journal.last_seq()', 'return\n            done, last = self.applied_seq(), self.journal.last_seq()', "TEST_HR_REGISTRY.py"),
    ("summary rows are imported as entities", "hr_core/importer.py",
     "elif not KEY.match(code):", "elif False:", "TEST_HR_REGISTRY.py"),
    ("the publisher ignores the registry", "eco_publisher.py",
     'if registry is not None and registry.list("employee"):', 'if False:', "TEST_HR_REGISTRY.py"),
    # phase 2: security and recovery (TEST_HR_SECURITY.py)
    ("journal signatures are not checked", "hr_core/journal.py",
     'if not r["sig"] or not signing.verify(pub, bytes.fromhex(r["hash"]), bytes.fromhex(r["sig"])):', 'if not r["sig"]:', "TEST_HR_SECURITY.py"),
    ("an unsigned line after signing began is accepted", "hr_core/journal.py",
     'elif signed_from is not None:', 'elif False:', "TEST_HR_SECURITY.py"),
    ("the server-side permission check is skipped", "hr_core/service.py",
     'if perm != "self" and perm not in self.auth.permissions(user):', 'if False:', "TEST_HR_SECURITY.py"),
    ("a disabled account keeps its open session", "hr_core/auth.py",
     'if s["last_seen"] < idle or s["created_at"] < oldest or not user or user["deleted"] or not user["active"]:', 'if s["last_seen"] < idle or s["created_at"] < oldest:', "TEST_HR_SECURITY.py"),
    ("a change without a version overwrites blindly", "hr_core/service.py",
     'if cur and expected_ver is None:', 'if False:', "TEST_HR_SECURITY.py"),
    ("account versions are not checked", "hr_core/auth.py",
     'if op.get("expected_ver") is not None and (not cur or cur["ver"] != op["expected_ver"]):', 'if False:', "TEST_HR_SECURITY.py"),
    ("wrong passwords never lock the account", "hr_core/auth.py",
     'if count >= MAX_FAILED else None', 'if False else None', "TEST_HR_SECURITY.py"),
    ("the last administrator can be disabled", "hr_core/auth.py",
     '                self._check_admin_remains()', '                pass', "TEST_HR_SECURITY.py"),
    ("cross-site requests are accepted", "hr_core/api.py",
     'if origin and urlparse(origin).netloc != self.headers.get("Host"):', 'if False:', "TEST_HR_SECURITY.py"),
    ("backup file hashes are not compared", "hr_core/backup.py",
     'elif _sha256(fp) != meta["sha256"] or os.path.getsize(fp) != meta["size"]:', 'elif False:', "TEST_HR_SECURITY.py"),
    ("the backup manifest signature is not checked", "hr_core/backup.py",
     'if pub is None or not sig or not signing.verify(pub, _manifest_digest(manifest), bytes.fromhex(sig)):', 'if False:', "TEST_HR_SECURITY.py"),
    ("the rehearsal does not compare the rebuild", "hr_core/backup.py",
     'checks["rebuilt_from_journal_identical"] = reg.fingerprint() == stored', 'checks["rebuilt_from_journal_identical"] = True', "TEST_HR_SECURITY.py"),
    ("a restore rolls history back instead of compensating", "hr_core/registry.py",
     'seq = self._append(actor, label, out, kind="restore")', 'self._wipe()\n            seq = self.journal.last_seq()', "TEST_HR_SECURITY.py"),
    ("a journal restored from a backup silently drops newer data", "hr_core/registry.py",
     'if not self.journal.follows(done, self.applied_hash()):', 'if False:', "TEST_HR_SECURITY.py"),
    ("a lost journal is replaced by an empty one", "hr_core/service.py",
     'restored_from = recover_lost_journal(data_dir, [backup_dir, *extra_backup_dirs])', 'restored_from, allow_new_journal = None, True', "TEST_HR_SECURITY.py"),
    ("the vendored BAMS signing file is edited", "hr_core/vendor/ed25519_bams.py",
     'def verify(pub, msg, sig):', 'def verify(pub, msg, sig):  # tidied', "TEST_HR_SECURITY.py"),
    ("the private device key is put into backups", "hr_core/backup.py",
     'files = {f: {"sha256"', 'shutil.copytree(os.path.join(self.data_dir, "node"), os.path.join(work, "node"))\n                files = {f: {"sha256"', "TEST_HR_SECURITY.py"),
    ("a shared connection runs statements without its lock", "hr_core/journal.py",
     "        with self._lock:\n            return _Rows(", "        if True:\n            return _Rows(", "TEST_HR_SECURITY.py"),
    ("the registry opens a plain connection again", "hr_core/registry.py",
     "self.db = SharedConnection(self.path, self.lock)", "self.db = SharedConnection(self.path, self.lock)._conn", "TEST_HR_SECURITY.py"),
    # phase 2.5: one installable product (TEST_HR_DELIVERY.py)
    ("the attendance engine answers without checking the right", "hr_core/api.py",
     'service.require(user, right, self.ip, f"attendance:{url.path}")', 'pass', "TEST_HR_DELIVERY.py"),
    ("setup is accepted from another computer", "hr_core/web.py",
     "if self.client_address[0] not in LOCAL:", "if False:", "TEST_HR_DELIVERY.py"),
    ("the company identity can be set twice", "hr_core/home.py",
     "        if self.company():\n            raise HomeError(\"company.set\"", "        if False:\n            raise HomeError(\"company.set\"", "TEST_HR_DELIVERY.py"),
    ("records open under another company id", "hr_core/registry.py",
     'if company and company["id"] != self.gid(', 'if False and company["id"] != self.gid(', "TEST_HR_DELIVERY.py"),
    ("the backup before an update is an ordinary one", "hr_core/upgrade.py",
     'made = svc.backups.create("upgrade", "pre-update")', 'made = svc.backups.create("upgrade", "manual")', "TEST_HR_DELIVERY.py"),
    ("data from a newer program is opened", "hr_core/upgrade.py",
     "    if found > DATA_VERSION:", "    if False:", "TEST_HR_DELIVERY.py"),
    ("a failed update leaves the half-updated data", "hr_core/upgrade.py",
     "        _put_back(home, marker)\n", "        pass\n", "TEST_HR_DELIVERY.py"),
    ("the data version is written before its step ran", "hr_core/upgrade.py",
     '            step(svc)\n            _fault(n, "after")\n            write_version(data, n)', '            write_version(data, n)\n            step(svc)\n            _fault(n, "after")', "TEST_HR_DELIVERY.py"),
    ("the update does not give the new rights", "hr_core/upgrade.py",
     "        if want != sorted(cur[\"perms\"] or []):", "        if False:", "TEST_HR_DELIVERY.py"),
    ("retention removes pre-update backups", "hr_core/backup.py",
     'names = sorted(n for n in os.listdir(d) if n.startswith("hr-") and', 'names = sorted(n for n in os.listdir(d) if n.startswith(("hr-", KEEP)) and', "TEST_HR_DELIVERY.py"),
    ("the attendance history is copied during an upload", "hr_core/backup.py",
     "                        with lock:\n                            if os.path.isfile(path):", "                        with threading.Lock():\n                            if os.path.isfile(path):", "TEST_HR_DELIVERY.py"),
    ("a recovery installer is kept without checking its hash", "hr_core/upgrade.py",
     ' and _sha256(exe).lower() == str(info.get("sha256", "")).lower()', "", "TEST_HR_DELIVERY.py"),
    ("start with Windows cannot be switched off", "hr_main.py",
     'if background and not cfg.get("autostart", True):', "if False:", "TEST_HR_DELIVERY.py"),
    ("regular assignments may overlap", "hr_core/scheduling.py",
     "        if o[\"kind\"] != row[\"kind\"]:\n            continue", "        if True:\n            continue", "TEST_HR_WORKFORCE.py"),
    ("a started assignment may change its shift", "hr_core/scheduling.py",
     "        if any(row.get(k) != cur.get(k) for k in fixed):", "        if False:", "TEST_HR_WORKFORCE.py"),
    ("a day before today can be re-planned", "hr_core/scheduling.py",
     "        if d < today:\n            raise ScheduleError(\"override.past\"", "        if False:\n            raise ScheduleError(\"override.past\"", "TEST_HR_WORKFORCE.py"),
    ("a night shift ends on its start day", "hr_core/scheduling.py",
     "end_day = start + timedelta(days=1) if overnight else start", "end_day = start", "TEST_HR_WORKFORCE.py"),
    ("a temporary assignment does not cover the regular one", "hr_core/scheduling.py",
     "chosen = next((a for a in covering if a[\"kind\"] == \"temporary\"), None) or next(", "chosen = next(", "TEST_HR_WORKFORCE.py"),
    ("a qualification never expires", "hr_core/service.py",
     "            if expiry:\n", "            if False:\n", "TEST_HR_WORKFORCE.py"),
    ("recertifying keeps the old automatic expiry", "hr_core/service.py",
     "                fields = dict(fields, expires_on=None)\n", "                pass\n", "TEST_HR_WORKFORCE.py"),
    ("a withdrawn qualification is still published as active", "eco_publisher.py",
     '"active": not q["deleted"] and', '"active": True or', "TEST_HR_WORKFORCE.py"),
    ("a shift's times change under past schedules", "hr_core/scheduling.py",
     "    if cur and in_use and any(", "    if False and any(", "TEST_HR_WORKFORCE.py"),
    ("the interface kit is changed here instead of in GMES", "hr_core/web/eco-ui/tokens.css",
     "  --eco-radius: 3px;", "  --eco-radius: 4px;", "TEST_HR_DELIVERY.py"),
    ("a screen writes a server message as HTML", "hr_core/web/app.js",
     "function fail(e) { ui.toast(", 'function fail(e) { document.body.insertAdjacentHTML("beforeend", e.message); ui.toast(', "TEST_HR_DELIVERY.py"),
    ("a menu name is missing from the dictionary", "hr_core/web/i18n/en.json",
     ' "nav.structure": "Structure",\n', "", "TEST_HR_DELIVERY.py"),
    ("an Arabic text is missing", "hr_core/web/i18n/ar.json",
     ' "cancel": "إلغاء",\n', "", "TEST_HR_DELIVERY.py"),
    ("the company identity is written before the administrator is checked", "hr_core/app.py",
     "            if not USERNAME.match(username):", "            if False:", "TEST_HR_DELIVERY.py"),
    ("backups are ordered by name instead of time", "hr_core/backup.py",
     "key=_age, reverse=True):  # by time", "reverse=True):  # by time", "TEST_HR_DELIVERY.py"),
    ("a refused attendance upload is audited as a change", "hr_core/api.py",
     'done = status == 200 and "error" not in reply and not reply.get("duplicate_upload")', "done = True", "TEST_HR_DELIVERY.py"),
    ("a file only Excel can open is handed to the engine on a PC without Excel", "hr_core/api.py",
     "            if excel_installed() is not False:\n                return False", "            if True:\n                return False", "TEST_HR_DELIVERY.py"),
    # ecosystem plan, Phase A: the installed product publishes to GMES by itself (hr_core/eco_link.py)
    ("the integration API returns the GMES key", "hr_core/eco_link.py",
     '"key_set": key is not None,', '"key_set": key is not None, "key": key,', "TEST_HR_DELIVERY.py"),
    ("the link to GMES starts although the address is empty", "hr_core/eco_link.py",
     '            if not cfg["gmes_url"]:\n                return False', '            if False:\n                return False', "TEST_HR_DELIVERY.py"),
    ("the integration settings change without the settings right", "hr_core/api.py",
     'service.require(user, "admin.settings.manage", h.ip, "integration:change")', 'pass', "TEST_HR_DELIVERY.py"),
    ("the GMES key is written into the audit", "hr_core/eco_link.py",
     'detail = dict(new, key="changed" if key is not None', 'detail = dict(new, key=key if key is not None', "TEST_HR_DELIVERY.py"),
    ("the link opens the registry with a writable connection", "hr_core/eco_link.py",
     '"hr.db"))).as_uri() + "?mode=ro", uri=True)', '"hr.db"))).as_uri() + "?mode=rwc", uri=True)', "TEST_HR_WORKFORCE.py"),
    # phase 6: discipline
    ("whoever proposes a violation may also decide it", "hr_core/service.py",
     'perm = "hr.discipline.approve" if deciding else WRITE_PERM[entity]', 'perm = WRITE_PERM[entity]', "TEST_HR_DISCIPLINE.py"),
    ("the deductions of a month are not capped", "hr_core/discipline.py",
     "    if days and deducted_in_month + days > MAX_MONTH_DEDUCTION:", "    if False:", "TEST_HR_DISCIPLINE.py"),
    ("a decided violation can be changed", "hr_core/discipline.py",
     '    if cur and not cur.get("deleted") and cur.get("status") in ("approved", "waived"):', "    if False:", "TEST_HR_DISCIPLINE.py"),
    # what manufacturing tells HR (WP-H1): machine keys, crew requirements, labour facts, the staffing gap
    ("a machine key without the inbox scope is accepted", "hr_core/eco_inbox.py",
     "        if scope not in row[\"scopes\"].split():", "        if False:", "TEST_HR_ECO_INBOX.py"),
    ("an event from another company is applied", "hr_core/eco_inbox.py",
     "        if len(parts) < 3 or parts[2].lower() != self.company_id:", "        if False:", "TEST_HR_ECO_INBOX.py"),
    ("an older crew requirement replaces a newer one", "hr_core/eco_inbox.py",
     "        cur = self.db.execute(\"SELECT version FROM crew_requirement WHERE id = ?\", (d[\"id\"],)).fetchone()\n        if cur and d[\"version\"] < cur[\"version\"]:",
     "        cur = self.db.execute(\"SELECT version FROM crew_requirement WHERE id = ?\", (d[\"id\"],)).fetchone()\n        if False:", "TEST_HR_ECO_INBOX.py"),
    ("an expired qualification covers a required skill", "hr_core/eco_inbox.py",
     'skills.state(q, day) in ("valid", "expiring")', "True", "TEST_HR_ECO_INBOX.py"),
    ("the staffing gap counts a person of another shift", "hr_core/eco_inbox.py",
     'people.setdefault((d["work_date"], d["shift_code"]), [])', 'people.setdefault((d["work_date"], "A"), [])', "TEST_HR_ECO_INBOX.py"),
    # people operations (WP-H2 to WP-H5): recruitment, overtime, training, leave
    ("a requisition is approved by the person who raised it", "hr_core/people_service.py",
     'if cur.get("created_by") == me:\n                            raise RegistryError("sod.own_requisition"', 'if False:\n                            raise RegistryError("sod.own_requisition"', "TEST_HR_PEOPLE_OPS.py"),
    ("overtime is approved by the person who asked for it", "hr_core/people_service.py",
     'if cur.get("requested_by") == me:\n                        raise RegistryError("sod.own_overtime"', 'if False:\n                        raise RegistryError("sod.own_overtime"', "TEST_HR_PEOPLE_OPS.py"),
    ("leave is approved by the person who entered it", "hr_core/people_service.py",
     'if cur.get("created_by") == me:\n                        raise RegistryError("sod.own_leave"', 'if False:\n                        raise RegistryError("sod.own_leave"', "TEST_HR_PEOPLE_OPS.py"),
    ("the headcount plan no longer limits a requisition", "hr_core/people_ops.py",
     'if asked + int(row["count"]) > planned and len(', 'if False and len(', "TEST_HR_PEOPLE_OPS.py"),
    ("a candidate is hired without an offer", "hr_core/people_service.py",
     'if cand["stage"] != "offered":', "if False:", "TEST_HR_PEOPLE_OPS.py"),
    ("a new hire is scheduled on a line before onboarding is done", "hr_core/registry.py",
     "            if cur is None:   # a new hire is not put on a production line", "            if False:   # a new hire is not put on a production line", "TEST_HR_PEOPLE_OPS.py"),
    ("a course lowers a qualification the person already holds", "hr_core/people_service.py",
     'level = max(level, int(cur["level"]))', "level = level", "TEST_HR_PEOPLE_OPS.py"),
    ("a training pass does not complete the onboarding task", "hr_core/people_service.py",
     '            if course.get("onboarding_kind"):', '            if False:', "TEST_HR_PEOPLE_OPS.py"),
    ("approved leave is not taken off the balance", "hr_core/people_ops.py",
     "    return entitlement + carried - used(year)", "    return entitlement + carried", "TEST_HR_PEOPLE_OPS.py"),
    ("days carry over for someone hired this year", "hr_core/people_ops.py",
     'employed_before = bool(emp and emp.get("hire_date") and str(emp["hire_date"]) < f"{year}-01-01")', "employed_before = True", "TEST_HR_PEOPLE_OPS.py"),
    ("two leave requests may cover the same days", "hr_core/people_ops.py",
     'if clash and row["status"] in ("requested", "approved"):', "if False:", "TEST_HR_PEOPLE_OPS.py"),
    ("overtime may take a day beyond the daily limit", "hr_core/people_ops.py",
     'if planned["status"] == "work" and minutes + planned["paid_minutes"] > p["max_daily_minutes_incl_ot"]:', "if False:", "TEST_HR_PEOPLE_OPS.py"),
    ("overtime is asked for on a day of approved leave", "hr_core/people_ops.py",
     '    if planned["status"] == "leave":', "    if False:", "TEST_HR_PEOPLE_OPS.py"),
    # the simulated date (WP-H7): an installed program can never be back-dated
    ("the date can be moved without the simulation switch", "hr_core/clock.py",
     "    if not enabled():\n        raise ClockError(\"clock.not_simulation\"", "    if False:\n        raise ClockError(\"clock.not_simulation\"", "TEST_HR_SIMULATION.py"),
    ("a person without the settings right moves the simulated date", "hr_core/api.py",
     'service.require(user, "admin.settings.manage", h.ip, "simulation:set")', "pass", "TEST_HR_SIMULATION.py"),
    # signed machine calls (WP-X2)
    ("a signature is accepted whatever the body", "eco_signing.py",
     '    want = sign_request(key_hash, method, path_with_query, raw_body, int(ts))', '    want = sign_request(key_hash, method, path_with_query, "", int(ts))', "TEST_HR_ECO_INBOX.py"),
    ("a stale signature is accepted", "eco_signing.py",
     "    if abs(now - int(ts)) > WINDOW_MS:", "    if False:", "TEST_HR_ECO_INBOX.py"),
    ("an unsigned call is accepted although signatures are required", "eco_signing.py",
     '        return "auth.signature_required" if required else None', "        return None", "TEST_HR_ECO_INBOX.py"),
    # WP-H6 payroll (TEST_HR_PAYROLL.py)
    ("a tax bracket rate is wrong", "hr_core/payroll_calc.py",
     "(200_000, 2000)", "(200_000, 2500)", "TEST_HR_PAYROLL.py"),
    ("the taxable income is not rounded down to ten pounds", "hr_core/payroll_calc.py",
     "income = annual_minor // (10 * POUND) * (10 * POUND)", "income = annual_minor", "TEST_HR_PAYROLL.py"),
    ("insurance is taken on the whole wage, above the maximum", "hr_core/payroll_calc.py",
     'base = div_half_up(clamp(int(profile["insurable_minor"]), r["si_min_minor"], r["si_max_minor"]) * num, den)', 'base = div_half_up(int(profile["insurable_minor"]) * num, den)', "TEST_HR_PAYROLL.py"),
    ("overtime is paid without its premium", "hr_core/payroll_calc.py",
     "(10_000 + premium_bp)", "(10_000)", "TEST_HR_PAYROLL.py"),
    ("a part month is paid in full", "hr_core/payroll_calc.py",
     'basic = div_half_up(profile["basic_minor"] * num, den)', 'basic = profile["basic_minor"]', "TEST_HR_PAYROLL.py"),
    ("unpaid leave is not deducted", "hr_core/payroll.py",
     'if lt is not None and str(lt.get("paid", 1)) == "0":', "if False:", "TEST_HR_PAYROLL.py"),
    ("the person who calculated a run can approve it", "hr_core/payroll.py",
     'if view["calculated_by"] == user["code"]:', "if False:", "TEST_HR_PAYROLL.py"),
    ("an approval does not check the fingerprint the approver saw", "hr_core/payroll.py",
     'if fingerprint != view["fingerprint"]:', "if False:", "TEST_HR_PAYROLL.py"),
    ("an approved run can be calculated again", "hr_core/payroll.py",
     'if latest and latest["status"] == "approved":', "if False:", "TEST_HR_PAYROLL.py"),
    ("a salary change can start inside an approved month", "hr_core/payroll.py",
     "if eff[:7] in self._locked_months():", "if False:", "TEST_HR_PAYROLL.py"),
    ("a reversal is sent with the same version", "hr_core/payroll.py",
     'self._stage(period, int(run), 2, "reversed")', 'self._stage(period, int(run), 1, "reversed")', "TEST_HR_PAYROLL.py"),
    ("anybody who may sign in can read the salaries", "hr_core/payroll.py",
     'self.require(user, "hr.payroll.read", ip, "payroll.profiles")', 'self.require(user, "self", ip, "payroll.profiles")', "TEST_HR_PAYROLL.py"),
    ("the pay database is left out of the backup", "hr_core/service.py",
     ", (PAYROLL_FILE, self._payroll_store.path, self._payroll_store.lock)", "", "TEST_HR_PAYROLL.py"),
    # project review 2026-10-02 (F01, F13, F14)
    ("approved leave can be edited by someone who may only write", "hr_core/people_service.py",
     'if cur and cur["status"] == "approved":', "if False:", "TEST_HR_PEOPLE_OPS.py"),
    ("leave over New Year is charged to its first year only", "hr_core/people_ops.py",
     "    if first.year == last.year:\n        return int(days) if first.year == year else 0", "    if True:\n        return int(days) if first.year == year else 0", "TEST_HR_PEOPLE_OPS.py"),
    ("the overtime policy is left out of the backup", "hr_core/service.py",
     ", (SETTINGS_FILE, self._settings.path, self._settings.lock)])", "])", "TEST_HR_PEOPLE_OPS.py"),
    ("a successful retry erases its rejection evidence", "hr_core/eco_inbox.py",
     "                # Retain the rejection record; status distinguishes unresolved source/event ids.", '                self.db.execute("DELETE FROM inbox_reject WHERE source = ? AND event_id = ?", (src, eid))', "TEST_HR_ECO_INBOX.py"),
    # stage 3.0: the continuity documents stay tied to the code (TEST_DOCS_CURRENT.py)
    ("a module's status changes without the documents", "hr_core/modules.py",
     '"depends_on": ["attendance", "leave", "overtime", "shifts"], "status": "built"', '"depends_on": ["attendance", "leave", "overtime", "shifts"], "status": "design_only"', "TEST_DOCS_CURRENT.py"),
    ("a new kernel file appears without the documents", "hr_core/shifts.py",
     None, '"""Shift definitions (not documented yet)."""\n', "TEST_DOCS_CURRENT.py"),
    ("an HTTP route changes without the documents", "hr_core/api.py",
     '@route("GET", "/api/me")', '@route("GET", "/api/whoami")', "TEST_DOCS_CURRENT.py"),
    ("a test no longer runs in CI", ".github/workflows/ci.yml",
     "      - run: python TEST_HR_REGISTRY.py\n", "", "TEST_DOCS_CURRENT.py"),
    ("the handoff names another phase than the status", "AGENT_HANDOFF.md",
     "```handoff\nphase: ", "```handoff\nphase: 9", "TEST_DOCS_CURRENT.py"),
    ("the design marks phase 3 done while the status does not", "docs/HR_SYSTEM_DESIGN.md",
     "| 3 | الورديات والجداول والتكليفات مستقلة", "| **3 (منفذة)** | الورديات والجداول والتكليفات مستقلة", "TEST_DOCS_CURRENT.py"),
    ("a history discovery loses its lesson", "HISTORY.md",
     "- **Lesson:** a document nobody", "- **Note:** a document nobody", "TEST_DOCS_CURRENT.py"),
    ("the status moves on without a history entry", "HISTORY.md",
     "## 2026-09-27 — Stage 3.0", "## 2026-09-26 — Stage 3.0", "TEST_DOCS_CURRENT.py"),
    ("the old attendance-only claim returns to the README", "README.md",
     "## ما يصل للعميل اليوم\n", "## ما يصل للعميل اليوم\n\nهذه النسخة هي أساس الحضور فقط.\n", "TEST_DOCS_CURRENT.py"),
    ("the shipped README links to a repository-only document", "README.md",
     "ابدأ من [دليل المستخدم](USER_GUIDE.md).", "ابدأ من [دليل المستخدم](USER_GUIDE.md) و[الحالة](STATUS.md).", "TEST_DOCS_CURRENT.py"),
    ("an outdated guide loses its historical banner", "PROJECT_GUIDE.md",
     "> **HISTORICAL (2026-09-05", "> **Note (2026-09-05", "TEST_DOCS_CURRENT.py"),
]

survived = 0
for name, rel, old, new, test in MUTATIONS:
    path = ROOT / rel
    if old is None:  # the planted bug is a new file
        if path.exists():
            sys.exit(f"mutation '{name}': {rel} already exists")
        original = None
        path.write_bytes(new.encode("utf-8"))
    else:
        # bytes, not text: on Windows write_text turns every LF into CRLF, which changed 14 files (hash-pinned ones too)
        original = path.read_bytes()
        if old.encode("utf-8") not in original:
            sys.exit(f"mutation '{name}': anchor not found in {rel}")
        path.write_bytes(original.replace(old.encode("utf-8"), new.encode("utf-8"), 1))
    try:
        env = dict(os.environ, PYTHONPATH=str(ROOT / "vendor.zip"))
        failed = subprocess.run([sys.executable, test], cwd=ROOT, env=env, capture_output=True).returncode != 0
    finally:
        if original is None:
            path.unlink()
        else:
            path.write_bytes(original)
    print(("caught    " if failed else "SURVIVED  ") + name)
    survived += 0 if failed else 1
subprocess.run(["git", "checkout", "--", "sample/"], cwd=ROOT, capture_output=True)
if survived:
    sys.exit(f"{survived} mutation(s) survived: a test is missing")
print("every planted bug was caught")
