"""Packs the screens (hr_core/web/) into hr_core/_assets.py, so the installed program carries them inside the compiled
program instead of as readable files (run by tools/build_windows.py; the module is never committed).

    python tools/make_assets.py [output]        default: hr_core/_assets.py
"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "hr_core", "web")


def collect():
    out = {}
    for base, _, files in os.walk(WEB):
        for f in sorted(files):
            path = os.path.join(base, f)
            with open(path, "rb") as fh:
                out[os.path.relpath(path, WEB).replace(os.sep, "/")] = fh.read()
    return dict(sorted(out.items()))


def write(target):
    lines = ['"""Generated by tools/make_assets.py from hr_core/web/ - do not edit, do not commit."""', "import base64", "", "FILES = {"]
    for name, data in collect().items():
        lines.append(f"    {name!r}: base64.b64decode({base64.b64encode(data).decode()!r}),")
    lines.append("}")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return target


if __name__ == "__main__":
    print(write(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "hr_core", "_assets.py")))
